CREATE TABLE WALLET (
  WALLET_ID        INT PRIMARY KEY AUTO_INCREMENT,
  USER_ID          VARCHAR(100),
  WALLET_TYPE      TINYINT,
  ADDRESS          CHAR(64),
  BALANCE          DECIMAL(13, 4),
  SEND_COINT_HASH  CHAR(64),
  SEND_COIN_AMOUNT DECIMAL(13, 4),
  CREATED_AT       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE WALLET_RESTORE (
  WALLET_RESTORE_ID INT PRIMARY KEY AUTO_INCREMENT,
  ADDRESS           CHAR(64),
  MNEMONIC          TEXT,
  PASSWORD          CHAR(64),
  CREATED_AT        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);